<?php
if (($angela_slider_sc = angela_get_theme_option('front_page_title_shortcode')) != '' && strpos($angela_slider_sc, '[')!==false && strpos($angela_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$angela_anchor_icon = angela_get_theme_option('front_page_title_anchor_icon');	
		$angela_anchor_text = angela_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($angela_anchor_icon) || !empty($angela_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($angela_anchor_icon) ? ' icon="'.esc_attr($angela_anchor_icon).'"' : '')
											. (!empty($angela_anchor_text) ? ' title="'.esc_attr($angela_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($angela_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$angela_scheme = angela_get_theme_option('front_page_title_scheme');
				if (!angela_is_inherit($angela_scheme)) echo ' scheme_'.esc_attr($angela_scheme);
				echo ' front_page_section_paddings_'.esc_attr(angela_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$angela_css = '';
			$angela_bg_image = angela_get_theme_option('front_page_title_bg_image');
			if (!empty($angela_bg_image)) 
				$angela_css .= 'background-image: url('.esc_url(angela_get_attachment_url($angela_bg_image)).');';
			if (!empty($angela_css))
				echo ' style="' . esc_attr($angela_css) . '"';
	?>><?php
		// Add anchor
		$angela_anchor_icon = angela_get_theme_option('front_page_title_anchor_icon');	
		$angela_anchor_text = angela_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($angela_anchor_icon) || !empty($angela_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($angela_anchor_icon) ? ' icon="'.esc_attr($angela_anchor_icon).'"' : '')
											. (!empty($angela_anchor_text) ? ' title="'.esc_attr($angela_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (angela_get_theme_option('front_page_title_fullheight'))
				echo ' angela-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$angela_css = '';
				$angela_bg_mask = angela_get_theme_option('front_page_title_bg_mask');
				$angela_bg_color = angela_get_theme_option('front_page_title_bg_color');
				if (!empty($angela_bg_color) && $angela_bg_mask > 0)
					$angela_css .= 'background-color: '.esc_attr($angela_bg_mask==1
																		? $angela_bg_color
																		: angela_hex2rgba($angela_bg_color, $angela_bg_mask)
																	).';';
				if (!empty($angela_css))
					echo ' style="' . esc_attr($angela_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$angela_caption = angela_get_theme_option('front_page_title_caption');
				if (!empty($angela_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($angela_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($angela_caption); ?></h1><?php
				}
			
				// Description (text)
				$angela_description = angela_get_theme_option('front_page_title_description');
				if (!empty($angela_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($angela_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($angela_description)); ?></div><?php
				}
				
				// Buttons
				if (angela_get_theme_option('front_page_title_button1_link')!='' || angela_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						angela_show_layout(angela_customizer_partial_refresh_front_page_title_button1_link());
						angela_show_layout(angela_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}